import './globals.css'
import type { Metadata } from 'next'
import {Aboreto} from 'next/font/google'
import NavBar from "@/app/components/NavBar";

const inter = Aboreto({ subsets: ['latin-ext'],weight:'400' })

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800">
      <NavBar/>
      {children}
      </body>
    </html>
  )
}
